image: debian/stable
packages:
  - build-essential
  - pkg-config
  - cmake
  - ninja-build
  - libgpgme-dev
  - libpython3-dev
  - python3-pip
sources:
  - https://git.sr.ht/~henrytill/gpgme-bits
tasks:
  - requirements: |
      cd gpgme-bits
      python3 -m pip install -r requirements.txt
  - setup: |
      cd gpgme-bits
      mkdir build-debug
      cmake -DCMAKE_BUILD_TYPE=Debug -GNinja -B build-debug
  - build: |
      cd gpgme-bits
      cmake --build build-debug
  - test: |
      cd gpgme-bits
      cmake --build build-debug --target test
